/* MINA ADMIN WIKI V6 CLEAN */
(function(window,document){"use strict";const CMS=()=>window.MinaCMS,CONFIG=()=>window.MinaCMSConfig;const state={skills:[],editingId:null,filter:"",imageBase64:"",imageName:""};
function unwrap(p){if(Array.isArray(p))return p;for(const k of ["skills","data","items","records"])if(Array.isArray(p?.[k]))return p[k];return[];}
function text(v){return CMS().text(v);}function normalize(r={}){return{...r,id:text(r.id),name:text(r.name),level:r.level??"",type:text(r.type),style:text(r.style),bpm:Number(r.bpm??r.bpmBest)||"",rarity:text(r.rarity).toUpperCase(),rating:Number(r.rating)||"",image:text(r.image??r.imageUrl),youtube:text(r.youtube??r.youtubeUrl),song:text(r.song),camera:text(r.camera??r.cameraAngle),description:text(r.description??r.notes),note:text(r.note),tags:Array.isArray(r.tags)?r.tags:text(r.tags).split(",").map(x=>x.trim()).filter(Boolean),reviewed:Boolean(r.reviewed),status:text(r.status)||(r.reviewed?"verified":"needs_review"),hot:Boolean(r.hot)};}
function getForm(){return document.getElementById("skillForm");}function backup(){localStorage.setItem(CONFIG().storage.draftKey,JSON.stringify(state.skills));}function getSkills(){return JSON.parse(JSON.stringify(state.skills));}
async function load(force=false){CMS().setBusy(true,"Đang tải dữ liệu skill...");try{const p=await CMS().request(`${CONFIG().api.skills}?v=${Date.now()}${force?"&force=1":""}`);state.skills=unwrap(p).map(normalize);backup();renderAll();CMS().toast(`Đã tải ${state.skills.length} skill.`,"success");}catch(err){const local=localStorage.getItem(CONFIG().storage.draftKey);state.skills=local?JSON.parse(local).map(normalize):[];renderAll();CMS().toast(err.message||"Không tải được dữ liệu, đang dùng bản nháp.","warning");}finally{CMS().setBusy(false);}}
function readForm(){const data=Object.fromEntries(new FormData(getForm()).entries());return normalize(data);}function resetForm(){getForm()?.reset();state.editingId=null;state.imageBase64="";state.imageName="";document.getElementById("skillImagePreview")?.replaceChildren();}
function fillForm(x){const f=getForm();if(!f)return;Object.entries(x).forEach(([k,v])=>{const field=f.elements.namedItem(k);if(field)field.value=Array.isArray(v)?v.join(", "):(v??"");});state.editingId=x.id;window.MinaAdminLayout?.activateTab("add");f.querySelector('[name="name"]')?.focus();}
async function save(ev){ev.preventDefault();const skill=readForm();if(!skill.id||!skill.name)return CMS().toast("Cần nhập ID và tên skill.","error");const dup=state.skills.find(x=>x.id.toLowerCase()===skill.id.toLowerCase()&&x.id!==state.editingId);if(dup)return CMS().toast("ID skill đã tồn tại.","error");CMS().setBusy(true,"Đang lưu và đồng bộ skill...");try{const body={skillData:skill};if(state.imageBase64){body.imageBase64=state.imageBase64;body.imageName=state.imageName||`skill-${skill.id}`;}const result=await CMS().request(CONFIG().api.saveSkill,{method:"POST",body:JSON.stringify(body)});const saved=normalize(result?.skill||result?.data||skill);const i=state.skills.findIndex(x=>x.id===state.editingId||x.id===saved.id);if(i>=0)state.skills[i]=saved;else state.skills.unshift(saved);backup();resetForm();renderAll();window.MinaWikiEngine?.clearCache?.();CMS().toast(`Đã ${i>=0?"cập nhật":"thêm"} skill và đồng bộ thành công.`,"success");CMS().emit("skills:changed",{action:i>=0?"update":"create",skill:saved});}catch(err){CMS().toast(err.message||"Không lưu được skill.","error");}finally{CMS().setBusy(false);}}
async function remove(id){const x=state.skills.find(s=>s.id===id);if(!x||!confirm(`Xóa skill "${x.name}" (${id})?`))return;CMS().setBusy(true,"Đang xóa skill...");try{await CMS().request(CONFIG().api.deleteSkill,{method:"POST",body:JSON.stringify({id})});state.skills=state.skills.filter(s=>s.id!==id);backup();renderAll();CMS().toast("Đã xóa skill và đồng bộ dữ liệu.","success");}catch(err){CMS().toast(err.message||"Không xóa được skill.","error");}finally{CMS().setBusy(false);}}
function filtered(){const q=state.filter.toLowerCase();return q?state.skills.filter(x=>[x.id,x.name,x.style,x.type,x.rarity].join(" ").toLowerCase().includes(q)):state.skills;}
function renderTable(){const b=document.getElementById("skillTable");if(!b)return;const rows=filtered();b.innerHTML=rows.length?rows.map(x=>`<tr><td>${CMS().escapeHTML(x.id)}</td><td>${CMS().escapeHTML(x.name)}</td><td>${CMS().escapeHTML(x.style)}</td><td>${CMS().escapeHTML(x.bpm)}</td><td><span class="rarity rarity-${CMS().escapeHTML(x.rarity)}">${CMS().escapeHTML(x.rarity||"-")}</span></td><td>${CMS().escapeHTML(x.rating)}</td><td>${x.youtube?"✓":"—"}</td><td>${x.status==="verified"?"Đã xác minh":"Cần review"}</td><td><button type="button" class="cms-btn" data-edit-id="${CMS().escapeHTML(x.id)}">Sửa</button> <button type="button" class="cms-btn danger" data-delete-id="${CMS().escapeHTML(x.id)}">Xóa</button></td></tr>`).join(""):`<tr><td colspan="9">Chưa có dữ liệu phù hợp.</td></tr>`;}
function renderStats(){const set=(id,v)=>{const x=document.getElementById(id);if(x)x.textContent=v;};set("totalSkill",state.skills.length);set("totalYoutube",state.skills.filter(x=>x.youtube).length);set("totalNeedReview",state.skills.filter(x=>x.status!=="verified").length);set("totalRareS",state.skills.filter(x=>x.rarity==="S").length);}
function renderYouTube(){const b=document.getElementById("youtubeList");if(!b)return;b.innerHTML=state.skills.map(x=>`<article class="youtube-item"><div><b>${CMS().escapeHTML(x.id)} — ${CMS().escapeHTML(x.name)}</b><small>${x.youtube?"Đã có video":"Chưa có video review"}</small></div><a class="cms-btn" target="_blank" rel="noopener" href="${x.youtube||`https://www.youtube.com/results?search_query=${encodeURIComponent(`Audition ${x.id} ${x.name}`)}`}">${x.youtube?"Mở video":"Tìm review"}</a></article>`).join("");}
function renderAll(){renderStats();renderTable();renderYouTube();}function exportJSON(){const blob=new Blob([JSON.stringify({version:1,updatedAt:new Date().toISOString(),skills:state.skills},null,2)],{type:"application/json"});const u=URL.createObjectURL(blob),a=Object.assign(document.createElement("a"),{href:u,download:"master-skills-backup.json"});a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function setSkills(list){state.skills=(list||[]).map(normalize);backup();renderAll();CMS().emit("skills:changed",{action:"replace",skills:getSkills()});}
function bind(){getForm()?.addEventListener("submit",save);document.getElementById("searchInput")?.addEventListener("input",CMS().debounce(ev=>{state.filter=ev.target.value.trim();renderTable();}));document.getElementById("skillTable")?.addEventListener("click",ev=>{const eid=ev.target.closest("[data-edit-id]")?.dataset.editId,did=ev.target.closest("[data-delete-id]")?.dataset.deleteId;if(eid)fillForm(state.skills.find(x=>x.id===eid));if(did)remove(did);});["exportJsonBtn","exportJsonBtn2"].forEach(id=>document.getElementById(id)?.addEventListener("click",exportJSON));document.getElementById("loadJsonBtn")?.addEventListener("click",()=>load(true));window.addEventListener("mina:image-ready",ev=>{state.imageBase64=ev.detail?.base64||"";state.imageName=ev.detail?.name||"";});}
async function init(){bind();await load();}window.MinaAdminWiki={init,load,getSkills,setSkills,renderAll};document.addEventListener("DOMContentLoaded",init,{once:true});})(window,document);
